version: '3'

services:

  db:
    image: postgres
    environment:
      - POSTGRES_DB=disk_accounting
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  main:
    build:
      context: .
      dockerfile: main-service/Dockerfile
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/disk_accounting
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    expose:
      - 8081

  report:
    build:
      context: .
      dockerfile: report-service/Dockerfile
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/disk_accounting
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    expose:
      - 8082

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    depends_on:
      - main
      - report
    ports:
      - "8083:8083"

volumes:
  pgdata: