version: '3'

services:

  db:
    image: postgres
    environment:
      - POSTGRES_DB=disk_accounting
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - ./data:/data
    command: server /data --console-address ":9001"

  main:
    build: ./main-service
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DATABASE_URL=jdbc:postgresql://db:5432/disk_accounting
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    expose:
      - 8081

  storage:
    build: ./storage-service
    depends_on:
      - report
      - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    expose:
      - 8080

  report:
    build: ./report-service
    depends_on:
      - main
      - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    expose:
      - 8082

  gateway:
    build: ./gateway
    depends_on:
      - main
      - report
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MAIN_ID=main
      - MAIN_URI=http://main:8081
      - MAIN_PREDICATE_PATH=/main/**
      - MAIN_FILTER_REWRITE_PATH=/main/(?<path>.*), /$$\{path}
      - MAIN_REMOVE_REQUEST_HEADER=Cookie, SetCookie
      - REPORT_ID=report
      - REPORT_URI=http://report:8082
      - REPORT_PREDICATE_PATH=/report/**
      - REPORT_FILTER_REWRITE_PATH=/report/(?<path>.*), /$$\{path}
      - REPORT_REMOVE_REQUEST_HEADER=Cookie, SetCookie
    ports:
      - "8083:8083"