version: '3'
services:
  main:
    build: ./main-service
    expose:
      - 8081
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/disk_accounting
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
  report:
    build: ./report-service
    expose:
      - 8082
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/disk_accounting
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
  gateway:
    build: ./gateway
    ports:
      - "8083:8083"
    depends_on:
      - main
      - report
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=disk_accounting
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432